set CREATEDLL_COMMAND=%1%
set DLL_BASE_NAME=%2%
set CONFIGURATION=%3%
set PLATFORM=%4%
set EXTRA_PATH=%5%

if "%CONFIGURATION%" == "Release" set DLL_NAME=%DLL_BASE_NAME%
if "%CONFIGURATION%" == "Debug"   set DLL_NAME=%DLL_BASE_NAME%d

if "%EXTRA_PATH%" == "" GOTO NO_EXTRA_PATH_ARG

:EXTRA_PATH_ARG

echo %CREATEDLL_COMMAND% -n"%CONFIGURATION%/%DLL_NAME%.map" -M%PLATFORM% -l"%DLL_BASE_NAME%.dir/%CONFIGURATION%" -l"%EXTRA_PATH%/%CONFIGURATION% -i"%CONFIGURATION%/%DLL_NAME%.lib"

%CREATEDLL_COMMAND% -n"%CONFIGURATION%/%DLL_NAME%.map" -M%PLATFORM% -l"%DLL_BASE_NAME%.dir/%CONFIGURATION%" -l"%EXTRA_PATH%/%CONFIGURATION% -i"%CONFIGURATION%/%DLL_NAME%.lib"

GOTO:eof

:NO_EXTRA_PATH_ARG

echo %CREATEDLL_COMMAND% -n"%CONFIGURATION%/%DLL_NAME%.map" -M%PLATFORM% -l"%DLL_BASE_NAME%.dir/%CONFIGURATION%" -i"%CONFIGURATION%/%DLL_NAME%.lib"

%CREATEDLL_COMMAND% -n"%CONFIGURATION%/%DLL_NAME%.map" -M%PLATFORM% -l"%DLL_BASE_NAME%.dir/%CONFIGURATION%" -i"%CONFIGURATION%/%DLL_NAME%.lib"

GOTO:eof
